#!/bin/bash

set -e

echo -e "\nStarting update\n"
        sudo apt update && \
        sudo apt upgrade -y && \
        sudo apt autoremove -y && \
        echo -e "\nUpdate done\n" || echo -e "\nUpdate Failed\n"
